build:
  cuda_version: "12.1.1"
  system_packages:
    - "libssl-dev"
    - "libx11-6"
    - "libxext6"
    - "libgl1-mesa-glx"
  python_packages:
    - "torch==2.2.1"
    - "opencv-python==4.9.0.80"
    - "transformers==4.38.1"
    - "diffusers==0.26.3"
    - "accelerate==0.27.2"
